apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-registry
  labels:
    app: ms-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-registry
  template:
    metadata:
      labels:
        app: ms-registry
    spec:
      containers:
      - name: ms-registry
        image: k3d-my-registry:5000/my-service:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: ms-env