common:
  name: nginx
  namespace: default
  labels:
    app: nginx-helm
  ports:
    http: 8080
    https: 8443
  selector:
    app: nginx-helm

deployment:
  apiVersion: apps/v1
  name: "{{ .Values.common.name }}-helm"
  namespace: "{{ .Values.common.namespace }}"
  labels: "{{ .Values.common.labels }}"
  matchLabels: "{{ .Values.common.selector }}"

podLabels:
  app: "{{ .Values.common.name }}-helm"
  tier: frontend

container:
  name: "{{ .Values.common.name }}-helm"
  image:
    repository: nginx
    tag: latest
  ports: "{{ .Values.common.ports }}"
 

service:
  name: "{{ .Values.common.name }}-helm"
  namespace: "{{ .Values.common.namespace }}"
  labels: "{{ .Values.common.labels }}"
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports: "{{ .Values.common.ports }}"
  targetPort: "{{ .Values.common.ports }}"
 
  extraPorts: []
  selector: "{{ .Values.common.selector }}"

metrics:
  enabled: false
  service:
    port: 9090

ingress:
  apiVersion: networking.k8s.io/v1
  name: "{{ .Values.common.name }}-helm"
  namespace: "{{ .Values.common.namespace }}"
  labels: "{{ .Values.common.labels }}"
  hostname: my-nginx.local
  path: /
  pathType: Prefix
  serviceName: "{{ .Values.common.name }}-helm"
  servicePort: 80
  tls: []  # Configure if TLS is needed
