common:
  name: nginx-helm
  namespace: default
  labels:
    app: nginx-helm
  ports:
    http: 8082
    https: 8443
  selector:
    app: nginx-helm

deployment:
  apiVersion: apps/v1
  matchLabels:
    app: nginx-helm

podLabels:
  tier: frontend
  app: nginx-helm

container:
  image:
    repository: nginx
    tag: latest

service:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports:
    http: 8082
  targetPort: 80
  extraPorts: []

metrics:
  enabled: false
  service:
    port: 9090

ingress:
  apiVersion: networking.k8s.io/v1
  hostname: nginx-helm.local
  path: /
  pathType: Prefix
  servicePort: 8082
  tls: []  # Configure if TLS is needed
