apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/belisky/fido-platform.git"
    targetRevision: HEAD
    path: infra-k8s/k8s-apps/my_service-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true