---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
  labels:
    app: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms
        image: k3d-my-registry:5000/my-service:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: ms-env