---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.namespace | quote }}
  labels: 
    {{- toYaml .Values.common.labels | nindent 4 }} 
spec:
  replicas: 1
  selector:
    matchLabels: 
      {{- toYaml .Values.common.selector | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- toYaml .Values.podLabels | nindent 8 }}       
    spec:         
      containers:
        - name: {{ .Values.common.name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.common.ports.http }}
            - name: https
              containerPort: {{ .Values.common.ports.https }}
         
