apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace | quote }}
  labels: 
    {{- toYaml .Values.service.labels | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  ports:
    {{- if .Values.service.ports.http }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.targetPort.http }}
  
    {{- end }}

    {{- if .Values.service.ports.https }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: {{ .Values.service.targetPort.https }}
   
    {{- end }}
 

  selector: 
    {{- toYaml .Values.service.selector | nindent 4 }}
