apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
 

spec:
  ports:
    - protocol: TCP
      port: {{ .Values.common.ports.http }}
      targetPort: 80
   
  selector:
    {{- toYaml .Values.common.selector | nindent 4 }}
