apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: fido-exam
servers: 1
agents: 3
registries:
  create: 
    name: my-registry
  config: |
    mirrors:
      "my-registry.local":
        endpoint:
          - http://my-registry.local:5000
ports:
  - port: 8090:8000
    nodeFilters:
      - loadbalancer
  - port: 8091:80
    nodeFilters:
      - loadbalancer
  - port: 8092:8082
    nodeFilters:
      - loadbalancer
  - port: 8093:8083
    nodeFilters:
      - loadbalancer
  - port: 8094:8084
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
